In [1]:
import pandas as pd

from src.screener.engine import ScreenerEngine

In [2]:
import os

print(os.listdir("../data/processed"))

['master_dataset.csv']

In [3]:
import pandas as pd

df = pd.read_csv("../data/processed/master_dataset.csv")

print(df.shape)
df.head()

(1208, 48)

,company_id,year,net_profit_margin_pct,operating_profit_margin_pct,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,free_cash_flow_cr,capex_cr,...,fixed_assets,cwip,investments,other_asset,total_assets,operating_activity,investing_activity,financing_activity,net_cash_flow,company_name
0,ABB,NaN,8.77,12.0,22.41,0.0,NaN,1.8225,42.0,59.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abbott India Ltd
1,ABB,NaN,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abbott India Ltd
2,ABB,NaN,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abbott India Ltd
3,ABB,NaN,10.00,14.0,24.44,0.0,NaN,1.6659,28.0,187.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abbott India Ltd
4,ABB,NaN,10.00,14.0,24.44,0.0,NaN,1.6659,-1899.0,1864.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abbott India Ltd

In [4]:
for col in df.columns:
    print(col)

company_id
year
net_profit_margin_pct
operating_profit_margin_pct
return_on_equity_pct
debt_to_equity
interest_coverage
asset_turnover
free_cash_flow_cr
capex_cr
earnings_per_share
book_value_per_share
dividend_payout_ratio_pct
total_debt_cr
cash_from_operations_cr
market_cap_crore
enterprise_value_crore
pe_ratio
pb_ratio
ev_ebitda
dividend_yield_pct
sales
expenses
operating_profit
opm_percentage
other_income
interest
depreciation
profit_before_tax
tax_percentage
net_profit
eps
dividend_payout
equity_capital
reserves
borrowings
other_liabilities
total_liabilities
fixed_assets
cwip
investments
other_asset
total_assets
operating_activity
investing_activity
financing_activity
net_cash_flow
company_name

In [5]:
import pandas as pd

from src.screener.engine import ScreenerEngine

In [6]:
df = pd.read_csv("../data/processed/master_dataset.csv")

print(df.shape)

(1208, 48)

In [7]:
filters = {
    "return_on_equity_pct": 15,
    "debt_to_equity": 1,
    "operating_profit_margin_pct": 10,
    "free_cash_flow_cr": 0,
    "pe_ratio": 30
}

In [8]:
engine = ScreenerEngine(df)

result = engine.apply_filters(filters)

result[
    [
        "company_name",
        "return_on_equity_pct",
        "debt_to_equity",
        "operating_profit_margin_pct",
        "free_cash_flow_cr",
        "pe_ratio",
        "composite_quality_score"
    ]
].head(20)

Empty DataFrame
Columns: [company_name, return_on_equity_pct, debt_to_equity, operating_profit_margin_pct, free_cash_flow_cr, pe_ratio, composite_quality_score]
Index: []